# Generated by Django 4.2.6 on 2023-10-28 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('mobile', models.CharField(max_length=10)),
                ('city', models.TextField()),
                ('pic', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
